[package]
name = "compatibility-suite"
version = "0.0.0"
edition = "2024"

[dev-dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
base64 = "0.23.1"
bytes = "1.5.0"
cucumber = "0.23.0"
itertools = "0.15.0"
lazy_static = "1.5.0"
maplit = "1.0.2"
pact_models = { version = "~1.3.14" }
pact_matching = { version = "~2.0.10" }
pact_mock_server = { version = "~2.2.5" }
pact_verifier = { version = "~1.4.4" }
pact_consumer = { version = "~1.4.9" }
regex = "1.10.2"
reqwest = { version = "0.13.4", default-features = false, features = ["json"] }
rocket = { version = "0.5.0", features = ["json"] }
rustls = { version = "0.23.43", features = ["ring"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
sxd-document = "0.3.2"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "tracing-log", "fmt"] }
uuid = { version = "1.5.0", features = ["v4"] }

[patch.crates-io]
pact_models = { path = "../rust/pact_models" }
pact_matching = { path = "../rust/pact_matching" }
pact_consumer = { path = "../rust/pact_consumer" }
pact-plugin-driver = { git = "https://github.com/pact-foundation/pact-plugins.git" }
pact_mock_server = { git = "https://github.com/pact-foundation/pact-core-mock-server.git" }

[[test]]
name = "v1_consumer"
harness = false

[[test]]
name = "v1_provider"
harness = false

[[test]]
name = "v2_consumer"
harness = false

[[test]]
name = "v2_provider"
harness = false

[[test]]
name = "v3"
harness = false

[[test]]
name = "v3_provider"
harness = false

[[test]]
name = "v3_message"
harness = false

[[test]]
name = "v4"
harness = false
