[unix]
build:
    conan install . --output-folder=build --build=missing
    cmake --preset conan-release
    cmake --build --preset conan-release

[windows]
build:
    conan install . --output-folder=build --build=missing
    cmake --preset conan-default
    cmake --build --preset conan-release

clean:
    rm -rf build
    rm CMakeUserPresets.json

[unix]
run: build
    LD_LIBRARY_PATH="./build:${LD_LIBRARY_PATH:-}" DYLD_LIBRARY_PATH="./build:${DYLD_LIBRARY_PATH:-}" ./build/pact-consumer

[windows]
run: build
    PATH="./build:${PATH:-}" ./build/Release/pact-consumer.exe
