[package]
name = "pact_matching"
version = "1.2.12"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
edition = "2021"
description = "Pact-Rust support library that implements request and response matching logic"
documentation = "https://docs.rs/pact_matching/"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[features]
default = ["datetime", "xml", "plugins", "multipart", "form_urlencoded"]
datetime = ["pact_models/datetime", "pact-plugin-driver?/datetime", "dep:chrono"] # Support for date/time matchers and expressions
xml = ["pact_models/xml", "pact-plugin-driver?/xml", "dep:sxd-document"] # support for matching XML documents
plugins = ["dep:pact-plugin-driver"]
multipart = ["dep:multer"] # suport for MIME multipart bodies
form_urlencoded = ["pact_models/form_urlencoded"] # suport for matching form urlencoded

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.98"
base64 = "0.22.1"
bytes = { version = "1.10.1", features = ["serde"] }
chrono = { version = "0.4.41", features = ["std", "clock"], default-features = false, optional = true }
difference = "2.0.0"
futures = "0.3.31"
hex = "0.4.3"
http = "1.3.0"
infer = "0.19.0"
itertools = "0.14.0"
lazy_static = "1.5.0"
lenient_semver = "0.4.2"
maplit = "1.0.2"
md5 = "0.7.0"
mime = "0.3.17"
multer = { version = "3.0.0", features = ["all"], optional = true }
nom = "7.1.3"
onig = "6.5.1"
pact_models = { version = "~1.3.0", default-features = false }
pact-plugin-driver = { version = "~0.7.4", optional = true, default-features = false }
rand = "0.9.1"
reqwest = { version = "0.12.20", default-features = false, features = ["rustls-tls-native-roots", "json"] }
semver = "1.0.26"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_urlencoded = "0.7.1"
sxd-document = { version = "0.3.2", optional = true }
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
tracing-core = "0.1.34"
tree_magic_mini = "3.1.6"
uuid = { version = "1.17.0", features = ["v4"] }

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
env_logger = "0.11.8"
googletest = "0.13.0"
hamcrest2 = "0.3.0"
test-log = { version = "0.2.17", features = ["trace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "tracing-log", "fmt"] }
ntest = "0.9.3"
pretty_assertions = "1.4.1"
rstest = "0.24.0"
