[workspace]
members = [
    "pact_*"
]
exclude = [
    "pact_mock_server",
    "pact_mock_server_cli"
]
resolver = "2"

[patch.crates-io]
# FFI Inmemory sink uses the global static `LOG_BUFFER` in the pact_matching crate. This is required to be the same
# version across all crates (i.e. mock server crate).
pact_matching = { version = "~1.2.8", path = "./pact_matching" }
# Issue 389 - Pull change into other crates
pact_models = { version = "~1.2.6", path = "./pact_models" }

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
