[workspace]
members = [
    "pact_*"
]
exclude = [
    "pact_wasm"
]
resolver = "2"

[patch.crates-io]
onig = { git = "https://github.com/rust-onig/rust-onig", default-features = false }
pact_models = { path = "pact_models" }