load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#### RUST ####
http_archive(
    name = "rules_rust",
    sha256 = "4a9cb4fda6ccd5b5ec393b2e944822a62e050c7c06f1ea41607f14c4fdec57a2",
    urls = ["https://github.com/bazelbuild/rules_rust/releases/download/0.25.1/rules_rust-v0.25.1.tar.gz"],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")
rules_rust_dependencies()

rust_register_toolchains(
    edition = "2021",
)

load("//:repositories.bzl", "repos")

repos()

load("//:deps.bzl", "deps")

deps()

load("//:create_crate.bzl", "create_crate_repositories")

create_crate_repositories()

load("//:create_pact_binaries.bzl", "create_pact_binaries")
