name: Pact-Rust Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - name: Install shared mime info DB
        if: runner.os == 'macOS'
        run: brew install shared-mime-info
      - name: Tests
        run: cargo test
        working-directory: rust
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Build Components
        run: cargo build
        working-directory: rust
      - name: Clippy
        if: runner.os == 'Linux'
        run: cargo clippy
        working-directory: rust

  v2-engine:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Tests
        run: cargo test
        working-directory: rust
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
          PACT_MATCHING_ENGINE: v2
          PACT_V2_MATCHING_LOG_EXECUTED_PLAN: 1

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         docker run --rm --user "$(id -u)":"$(id -g)" -v $(pwd):/workspace -w /workspace/rust -t -e TZ=UTC pactfoundation/rust-musl-build ./scripts/ci-musl-build.sh


  check-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check --no-default-features
        working-directory: rust
