name: Pact-Rust FFI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Generic
  FORCE_COLOR: '1'
  CLICOLOR: '1'
  # Rust
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-13, macos-latest ]
        rust: [ stable ]
    env:
      pact_do_not_track: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install cbindgen
        uses: taiki-e/install-action@main
        with:
          tool: cbindgen


      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install shared-mime-info

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install curl --version=8.7.1
          choco install openssl

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Run C consumer examples
        working-directory: c/consumer
        run: make run

      - name: Run mock_server_logs test
        run: cargo test -p pact_ffi returns_mock_server_logs -- --nocapture --include-ignored
        working-directory: rust
